export const STORAGE_SENDING_MESSAGES_TYPES = {
    SYNC_SETTINGS: 'SYNC_SETTINGS',
    SYNC_PLUGIN_STATUS: 'SYNC_PLUGIN_STATUS',
    REMOTE_PLUGIN_STATUS_UPDATE: 'REMOTE_PLUGIN_STATUS_UPDATE',
    OPEN_SETTINGS_PAGE: 'OPEN_SETTINGS_PAGE',
} as const;

export const STORAGE_RECIEVING_MESSAGES_TYPES = {
    SUCCESSFUL: 'SUCCESSFUL',
} as const;

export const INTERNAL_STORAGE_PREFIX = {
    [STORAGE_SENDING_MESSAGES_TYPES.SYNC_SETTINGS]: 'setting',
    [STORAGE_SENDING_MESSAGES_TYPES.SYNC_PLUGIN_STATUS]: 'status',
};

export const STORAGE_SENDING_MESSAGES_TYPES_KEYS = Object.keys(STORAGE_SENDING_MESSAGES_TYPES) as any as keyof typeof STORAGE_RECIEVING_MESSAGES_TYPES;
export const STORAGE_RECIEVING_MESSAGES_TYPES_KEYS = Object.keys(STORAGE_RECIEVING_MESSAGES_TYPES) as any as keyof typeof STORAGE_RECIEVING_MESSAGES_TYPES;